### ISSUE TITLE
oc-installer does not understand semver, can't install 3.11.375-1

### ISSUE THREAD

**Issue by anthonydahanne** [redhat-actions/oc-installer#13]
### Version

redhat-actions/oc-installer@v1

### Describe the bug

oc-installer does not understand `oc_version` such as `3.11.375-1` (it will strip anything after the bugfix number, in this case, it will change the input to 3.11.375)   - works great with `3.11.374` though.

### Steps to reproduce, workflow links, screenshots

With such configuration:

```
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '3.11.375-1'
```

oc-installer will fail to install `oc` :

```
Run redhat-actions/oc-installer@v1
  with:
    oc_version: 3.11.375-1

Installing oc version 3.11.375
Found oc version 3.11.375 at https://mirror.openshift.com/pub/openshift-v3/clients/3.11.375/linux/oc.tar.gz
Downloading oc from https://mirror.openshift.com/pub/openshift-v3/clients/3.11.375/linux/oc.tar.gz ...
Error: Error: Unexpected HTTP response: 404

```

Although 3.11.375-1 exists: https://mirror.openshift.com/pub/openshift-v3/clients/3.11.375-1/linux/

**Comment by tetchel** [comment]
is using the url input type an acceptable workaround? the code seems to be rather rigid in this.

```yaml
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: 'https://mirror.openshift.com/pub/openshift-v3/clients/3.11.375-1/linux/oc.tar.gz'
```
