### ISSUE TITLE
Unable to resolve action `redhat-actions/oc-installer@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by DarkLite1** [redhat-actions/oc-installer#6]
Since this morning we receive the following error and our builds are no longer triggered:

> Unable to resolve action `redhat-actions/oc-installer@v1`, unable to find version `v1`

This is our GitHub workflow:
```yaml
name: Continuous deployment

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run OpenShift build process
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '3.11.230'         
      - name: Execute oc commands
        run: |
          oc login --insecure-skip-tls-verify --token ${{ secrets.OPENSHIFT_API_TOKEN }} ${{ secrets.OPENSHIFT_SERVER_URL }}
          oc project hip
          oc start-build backend-graphql-server --follow
```

Is there something we need to change?
